INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (1, 'Acre', 'AC', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (2, 'Alagoas', 'AL', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (3, 'Amazonas', 'AM', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (4, 'Amapá', 'AP', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (5, 'Bahia', 'BA', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (6, 'Ceará', 'CE', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (7, 'Distrito Federal', 'DF', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (8, 'Espírito Santo', 'ES', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (9, 'Goiás', 'GO', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (10, 'Maranhão', 'MA', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (11, 'Minas Gerais', 'MG', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (12, 'Mato Grosso do Sul', 'MS', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (13, 'Mato Grosso', 'MT', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (14, 'Pará', 'PA', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (15, 'Paraíba', 'PB', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (16, 'Pernambuco', 'PE', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (17, 'Piauí', 'PI', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (18, 'Paraná', 'PR', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (19, 'Rio de Janeiro', 'RJ', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (20, 'Rio Grande do Norte', 'RN', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (21, 'Rondônia', 'RO', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (22, 'Roraima', 'RR', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (23, 'Rio Grande do Sul', 'RS', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (24, 'Santa Catarina', 'SC', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (25, 'Sergipe', 'SE', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (26, 'São Paulo', 'SP', 1);
INSERT INTO `estado` (`id`, `nome`, `uf`, `pais`) VALUES (27, 'Tocantins', 'TO', 1);
